project:
  type: website

website:
  title: Project 2 - State Constitution Analysis
  navbar:
    right:
      - icon: github
        href: https://github.com/math241s24/project-02-state_constitution
    left:
      - text: "Write-up"
        href: index.qmd
      - text: "Proposal"
        href: proposal.qmd
      - text: "Presentation"
        href: presentation.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    theme: default
    toc: true

execute:
  freeze: auto

